esphome:
  name: alarm-bridge
  friendly_name: alarm-bridge

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Alarm-Bridge"
    password: !secret default_ap_password

captive_portal:

web_server:
  port: 80
  include_internal: True
  auth:
    username: admin
    password: admin
  ota: False
  local: True

# binary sensors for the alarm panel's aux output
# In this instance, aux 1 should not be connected to anything that may survive a
# power loss as it could potentially inadvertently put the ESP8266 into boot mode
# aux 2 and aux 3 has a 5 seconds delay to avoid race condition with the ness integration
# change the PIN definition / on delay time to suit your needs
binary_sensor:
  # Aux 1, unused for now
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: aux1
    name: "Aux 1"

  # Aux 2, Armed Away
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    id: aux2
    name: "Aux 2"
    filters:
      delayed_on: 5s

  # Aux 3, Armed Home
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    id: aux3
    name: "Aux 3"
    filters:
      delayed_on: 5s

  # Aux 4
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    id: aux4
    name: "Aux 4"

# you don't have to include these, I have these in order for it to communicate with my BI server
switch: 
- platform: gpio
  pin: 12
  id: relay_1
  name: "Front"
  internal: True
  on_turn_on:
    then:
    - delay: 5s
    - switch.turn_off: relay_1
- platform: gpio
  pin: 5
  id: relay_2
  name: "Side"
  internal: True
  on_turn_on:
    then:
    - delay: 5s
    - switch.turn_off: relay_2
- platform: gpio
  pin: 4
  id: relay_3
  name: "Back"
  internal: True
  on_turn_on:
    then:
    - delay: 5s
    - switch.turn_off: relay_3
- platform: gpio
  pin: 15
  id: relay_4
  name: "Backyard"
  internal: True
  on_turn_on:
    then:
    - delay: 5s
    - switch.turn_off: relay_4

status_led:
  pin: 13
